name: Build-Test-Deploy-Cloud-Run
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT: ${{secrets.GCP_PROJECT}}
    steps:
      - name: GCLOUD AUTH
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON}}
          export_default_credentials: true
    
      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}

      - name: Git checkout
        uses: actions/checkout@v2
        with:
          ref: main
      
      - name: GCP docker creds
        run: |
          make gcloud-docker-auth-cli

      - name: Prepare CI image
        run: |
          make get-img DOCKER_LAYER=dev PUSH_IMAGE=true

      - name: Test
        run: |
          make test

      - name: Build & Push app image 
        run: |
          (make _build-img DOCKER_LAYER=app) && (make push-img DOCKER_LAYER=app) && (echo "APP_IMAGE=$(make get-app-image-registry)" >> $GITHUB_ENV)
      
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: python-api-boilerplate 
          image: ${{ env.APP_IMAGE }}
          credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
          region: europe-west1
      
      - name: Get deploy URL
        run: curl "${{ steps.deploy.outputs.url }}"